SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS WHERE TABLE_CATALOG = 'DEMO';

USE SCHEMA SNOWFLAKE.ACCOUNT_USAGE;

SELECT 
    QUERY_TYPE, 
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CS_CREDITS, 
    COUNT(1) AS NUM_QUERIES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('DAY', -10, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

-- Find warehouses that consume the most cloud services credits
SELECT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE,
    SUM(CREDITS_USED) AS CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('DAY', -100, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME
ORDER BY CREDITS_USED DESC
LIMIT 10;